include:
  # Cheapino V2
  - board: rp2040_zero
    shield: cheapinov2
    snippet: studio-rpc-usb-uart
    artifact-name: cheapinov2-rp2040_zero
  - board: rp2040_zero
    shield: cheapinov2 settings_reset
    artifact-name: settings_reset-rp2040_zero
  # Ergonaut One
  - board: xiao_ble//zmk
    shield: ergonaut_one_left
    artifact-name: ergonaut_one_left-xiao_ble
  - board: xiao_ble//zmk
    shield: ergonaut_one_right
    artifact-name: ergonaut_one_right-xiao_ble
  - board: xiao_ble//zmk
    shield: settings_reset
    artifact-name: settings_reset-xiao_ble
  # Kinesis Advantage 360 Pro
  - board: adv360pro_left//zmk
    artifact-name: adv360pro_left
  - board: adv360pro_right//zmk
    artifact-name: adv360pro_right
  - board: adv360pro_left//zmk
    shield: settings_reset
    artifact-name: settings_reset-adv360pro_left
  - board: adv360pro_right//zmk
    shield: settings_reset
    artifact-name: settings_reset-adv360pro_right
