include:
  # Cheapino V2
  - board: nice_nano_v2
    shield: cheapinov2
    snippet: studio-rpc-usb-uart
  # Ergonaut One
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_left
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_right
  # Settings reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
