include:
  # Cheapino V2
  - board: nice_nano_v2
    shield: cheapinov2
    snippet: studio-rpc-usb-uart
  # Ergonaut One
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_left
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_right
  - board: seeeduino_xiao_ble
    shield: settings_reset
  # Kinesis Advantage 360 Pro
  - board: adv360pro_left
  - board: adv360pro_right
  - board: adv360pro_left
    shield: settings_reset
